In [1]:
import numpy as np

In [3]:
np.linspace(0, 10, 15) #0~15の区間を15等分

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c.shape

(2, 3)

In [7]:
d  = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],[10, 11, 12]], [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [8]:
d.shape

(2, 4, 3)

In [14]:
print(np.sum(c))
print("================")
print(np.sum(c, axis=1))
print("================")
print(c.reshape(3, 2))
print("================")
print(c.T)
print(np.transpose(c))

21
[ 6 15]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [15]:
print(np.random.rand()) 　#0~1までの乱数
print("================")
print(np.random.rand(2, 3))　#2行3列で乱数を生成
print("================")
print(np.random.randn())　#標準正規分布に従った値
print("================")
print(np.random.randn(2,3))　#2行3列で標準正規分布に従った値を生成

0.7492597435025926
[[0.53302433 0.59389482 0.52717033]
 [0.93817414 0.37175257 0.1402062 ]]
-0.2897655867397107
[[-0.03915944  1.83587637 -1.05521094]
 [ 0.07595947  2.29698897 -0.35996233]]
